### PR TITLE
Add install external plugins

### PR DESCRIPTION
**Pull request by ncharlot**
This feature allow to install external plugins from local files or download them.
We often need more plugins. For i.e. Redis, Varnish and many more.

### CODE REVIEW

**Comment by ncharlot** [comment]
Hi @geerlingguy!

What about this PR?

**Comment by ncharlot** [comment]
Hi @geerlingguy! We've been using this feature for months in production and it's very usefull to complete the monitoring (Memcached, etc.). And No BC there!

**Comment by quotengrote** [comment]
Hi, any news on this?

**Comment by lionslair** [comment]
bump

**Comment by ncharlot** [comment]
Hi @geerlingguy! Just seen you've "planned" my PR six months ago :sunglasses: An ETA?
Tell-me if I need to change something. Thx for you work

**Comment by zorun** [comment]
Good idea! I currently copy plugins outside of the role, but having this built-in into the role would be simpler.

**Pull request merged**
